
const ActionType = {
    GET_WORKSPACES: 'GET_WORKSPACES',
    SET_WORKSPACES: 'SET_WORKSPACES',
    ADD_WORKSPACE: 'ADD_WORKSPACE',
    GET_PROJECTS: 'GET_PROJECTS',
    DELETE_WORKSPACE: 'DELETE_WORKSPACE',
    SET_PROJECTS: 'SET_PROJECTS',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    GET_MEMBERS: 'GET_MEMBERS',
    SET_MEMBERS: 'SET_MEMBERS',
    NEW_MEMBER: 'NEW_MEMBER',
    NEW_PROJECT: 'NEW_PROJECT',
    NEW_WORKSPACE: 'NEW_WORKSPACE',
    UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
    DELETE_MEMBER: 'DELETE_MEMBER',
    GET_BOARD: 'GET_BOARD',
    NEW_BOARD: 'NEW_BOARD',
    EDIT_BOARD: 'EDIT_BOARD',
    DELETE_BOARD: 'DELETE_BOARD',
    NEW_ASPECT: 'NEW_ASPECT',
    EDIT_ASPECT: 'EDIT_ASPECT',
    DELETE_ASPECT: 'DELETE_ASPECT',
    NEW_SPRINT: 'NEW_SPRINT',
    EDIT_SPRINT: 'EDIT_SPRINT',
    DELETE_SPRINT: 'DELETE_SPRINT',
    GET_CHAT: 'GET_CHAT',
    SET_CHAT:  'SET_CHAT',
    INIT_CHAT: 'INIT_CHAT',
    POST_MESSAGE: 'POST_MESSAGE'
};

export default ActionType;