
const ActionType = {
    GET_WORKSPACES: 'GET_WORKSPACES',
    SET_WORKSPACES: 'SET_WORKSPACES',
    ADD_WORKSPACE: 'ADD_WORKSPACE',
    GET_PROJECTS: 'GET_PROJECTS',
    SET_PROJECTS: 'SET_PROJECTS',
    GET_MEMBERS: 'GET_MEMBERS',
    SET_MEMBERS: 'SET_MEMBERS',
    NEW_MEMBER: 'NEW_MEMBER',
    NEW_PROJECT: 'NEW_MEMBER',
    DELETE_MEMBER: 'DELETE_MEMBER'
};

export default ActionType;