
const ActionType = {
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
    UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
    UPDATE_AVATAR: 'UPDATE_AVATAR',
    GET_WORKSPACES: 'GET_WORKSPACES',
    SET_WORKSPACES: 'SET_WORKSPACES',
    ADD_WORKSPACE: 'ADD_WORKSPACE',
    GET_PROJECTS: 'GET_PROJECTS',
    SET_PROJECTS: 'SET_PROJECTS',
    GET_MEMBERS: 'GET_MEMBERS',
    SET_MEMBERS: 'SET_MEMBERS',
};

export default ActionType;